package com.lexi.flashcards.core.fsrs

import com.lexi.flashcards.core.model.CardState
import com.lexi.flashcards.core.model.FsrsCardState
import com.lexi.flashcards.core.model.Rating
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Cross-validates this Kotlin port against the reference Python implementation
 * (https://github.com/open-spaced-repetition/py-fsrs). Expected values in these
 * tests were generated by running the real py-fsrs `Scheduler` (fuzzing disabled)
 * with the exact same rating/timing sequences - see the task notes for the
 * generator script. Any change to the algorithm that breaks these tests is a
 * divergence from the reference model, not a "fix".
 */
class FsrsSchedulerTest {

    private val t0 = 1_767_225_600_000L // 2026-01-01T00:00:00Z
    private val dayMs = MILLIS_PER_DAY
    private val eps = 1e-6

    private fun newScheduler() = FsrsScheduler(enableFuzzing = false)

    private fun assertClose(expected: Double, actual: Double, message: String) {
        assertTrue(kotlin.math.abs(expected - actual) < eps, "$message: expected=$expected actual=$actual")
    }

    @Test
    fun `repeated Good walks through learning steps then grows stability in review`() {
        val scheduler = newScheduler()
        var card = FsrsCardState()

        val r1 = scheduler.review(card, Rating.GOOD, t0)
        card = r1.card
        assertEquals(CardState.LEARNING, card.state)
        assertEquals(1, card.step)
        assertClose(2.3065, card.stability!!, "stability after 1st Good")
        assertClose(2.118103970459016, card.difficulty!!, "difficulty after 1st Good")
        assertEquals(t0 + 600_000L, card.due)

        val r2 = scheduler.review(card, Rating.GOOD, t0)
        card = r2.card
        assertEquals(CardState.REVIEW, card.state)
        assertEquals(null, card.step)
        assertClose(2.3065, card.stability!!, "stability after 2nd Good")
        assertClose(2.111214235785395, card.difficulty!!, "difficulty after 2nd Good")
        assertEquals(1_767_398_400_000L, card.due)

        val t2 = t0 + 1 * dayMs
        val r3 = scheduler.review(card, Rating.GOOD, t2)
        card = r3.card
        assertClose(7.319186097840142, card.stability!!, "stability after 3rd Good")
        assertClose(2.1043313908464483, card.difficulty!!, "difficulty after 3rd Good")
        assertEquals(1_767_916_800_000L, card.due)

        val t3 = t2 + 5 * dayMs
        val r4 = scheduler.review(card, Rating.GOOD, t3)
        card = r4.card
        assertClose(26.272179620346094, card.stability!!, "stability after 4th Good")
        assertClose(2.0974554287524403, card.difficulty!!, "difficulty after 4th Good")
        assertEquals(1_769_990_400_000L, card.due)
    }

    @Test
    fun `Easy on a fresh card jumps straight into long-term review`() {
        val scheduler = newScheduler()
        val card = FsrsCardState()

        val result = scheduler.review(card, Rating.EASY, t0)

        assertEquals(CardState.REVIEW, result.card.state)
        assertEquals(null, result.card.step)
        assertClose(8.2956, result.card.stability!!, "initial Easy stability")
        assertClose(1.0, result.card.difficulty!!, "initial Easy difficulty")
        assertEquals(1_767_916_800_000L, result.card.due)
    }

    @Test
    fun `Again twice then Good twice recovers a fresh card into review`() {
        val scheduler = newScheduler()
        var card = FsrsCardState()

        card = scheduler.review(card, Rating.AGAIN, t0).card
        assertEquals(CardState.LEARNING, card.state)
        assertEquals(0, card.step)
        assertClose(0.212, card.stability!!, "stability after 1st Again")
        assertClose(6.4133, card.difficulty!!, "difficulty after 1st Again")

        card = scheduler.review(card, Rating.AGAIN, t0).card
        assertClose(0.08335671711031604, card.stability!!, "stability after 2nd Again")
        assertClose(8.806304468856837, card.difficulty!!, "difficulty after 2nd Again")

        card = scheduler.review(card, Rating.GOOD, t0).card
        assertEquals(CardState.LEARNING, card.state)
        assertEquals(1, card.step)
        assertClose(0.10314065007785231, card.stability!!, "stability after Good (step 1)")
        assertClose(8.792726533684817, card.difficulty!!, "difficulty after Good (step 1)")

        val result = scheduler.review(card, Rating.GOOD, 1_767_398_400_000L)
        assertEquals(CardState.REVIEW, result.card.state)
        assertClose(0.8433549877776628, result.card.stability!!, "stability entering review")
        assertClose(8.77916217644797, result.card.difficulty!!, "difficulty entering review")
        assertEquals(1_767_484_800_000L, result.card.due)
    }

    @Test
    fun `forgetting a review card sends it to relearning and increments lapses`() {
        val scheduler = newScheduler()
        var card = FsrsCardState()

        card = scheduler.review(card, Rating.GOOD, t0).card
        card = scheduler.review(card, Rating.GOOD, t0).card
        assertEquals(CardState.REVIEW, card.state)
        assertEquals(0, card.lapses)

        val t2 = 1_767_657_600_000L
        card = scheduler.review(card, Rating.GOOD, t2).card
        assertClose(18.180153970030403, card.stability!!, "stability before lapse")
        assertEquals(1_769_212_800_000L, card.due)

        val t3 = 1_769_385_600_000L
        val lapseResult = scheduler.review(card, Rating.AGAIN, t3)
        card = lapseResult.card
        assertEquals(CardState.RELEARNING, card.state)
        assertEquals(0, card.step)
        assertEquals(1, card.lapses)
        assertClose(1.98377481221205, card.stability!!, "stability right after forgetting")
        assertClose(7.389975788014609, card.difficulty!!, "difficulty right after forgetting")
        assertEquals(t3 + 600_000L, card.due)

        val backToReview = scheduler.review(card, Rating.GOOD, t3)
        assertEquals(CardState.REVIEW, backToReview.card.state)
        assertClose(1.992528433368568, backToReview.card.stability!!, "stability back in review")
        assertClose(7.377814181523433, backToReview.card.difficulty!!, "difficulty back in review")
        assertEquals(1_769_558_400_000L, backToReview.card.due)
    }

    @Test
    fun `repeated Hard never advances past the first learning step`() {
        val scheduler = newScheduler()
        var card = FsrsCardState()

        card = scheduler.review(card, Rating.HARD, t0).card
        assertEquals(CardState.LEARNING, card.state)
        assertEquals(0, card.step)
        assertClose(1.2931, card.stability!!, "stability after 1st Hard")
        assertClose(5.112170705601056, card.difficulty!!, "difficulty after 1st Hard")
        assertEquals(t0 + 330_000L, card.due)

        card = scheduler.review(card, Rating.HARD, t0).card
        assertEquals(0, card.step)
        assertClose(1.2931, card.stability!!, "stability after 2nd Hard")
        assertClose(6.7404595108297, card.difficulty!!, "difficulty after 2nd Hard")

        val t1 = t0 + 1 * dayMs
        card = scheduler.review(card, Rating.HARD, t1).card
        assertEquals(0, card.step)
        assertClose(2.7083905526720984, card.stability!!, "stability after 3rd Hard")
        assertClose(7.821393497998797, card.difficulty!!, "difficulty after 3rd Hard")
        assertEquals(t1 + 330_000L, card.due)
    }

    @Test
    fun `retrievability decays as elapsed time grows`() {
        val scheduler = newScheduler()
        var card = FsrsCardState()
        card = scheduler.review(card, Rating.GOOD, t0).card
        card = scheduler.review(card, Rating.GOOD, t0).card
        val t1 = t0 + 1 * dayMs
        card = scheduler.review(card, Rating.GOOD, t1).card

        assertClose(7.319186097840142, card.stability!!, "stability")

        assertClose(1.0, scheduler.getRetrievability(card, t1 + 0 * dayMs), "R at 0 days")
        assertClose(0.9808036913594662, scheduler.getRetrievability(card, t1 + 1 * dayMs), "R at 1 day")
        assertClose(0.9492481660614618, scheduler.getRetrievability(card, t1 + 3 * dayMs), "R at 3 days")
        assertClose(0.8771694810475593, scheduler.getRetrievability(card, t1 + 10 * dayMs), "R at 10 days")
    }

    @Test
    fun `previewIntervals never rates Again longer than Easy for a mature review card`() {
        val scheduler = FsrsScheduler(enableFuzzing = false)
        var card = FsrsCardState()
        card = scheduler.review(card, Rating.GOOD, t0).card
        card = scheduler.review(card, Rating.GOOD, t0).card

        val preview = scheduler.previewIntervals(card, t0)

        assertTrue(preview.getValue(Rating.AGAIN) <= preview.getValue(Rating.GOOD))
        assertTrue(preview.getValue(Rating.GOOD) <= preview.getValue(Rating.EASY))
    }
}
